########## MACROS ###########################################################################
#############################################################################################

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


########### FOUND PACKAGE ###################################################################
#############################################################################################

include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated FindSnappy.cmake")
set(Snappy_FOUND 1)
set(Snappy_VERSION "1.1.9")

find_package_handle_standard_args(Snappy REQUIRED_VARS
                                  Snappy_VERSION VERSION_VAR Snappy_VERSION)
mark_as_advanced(Snappy_FOUND Snappy_VERSION)

set(Snappy_COMPONENTS Snappy::snappy)

if(Snappy_FIND_COMPONENTS)
    foreach(_FIND_COMPONENT ${Snappy_FIND_COMPONENTS})
        list(FIND Snappy_COMPONENTS "Snappy::${_FIND_COMPONENT}" _index)
        if(${_index} EQUAL -1)
            conan_message(FATAL_ERROR "Conan: Component '${_FIND_COMPONENT}' NOT found in package 'Snappy'")
        else()
            conan_message(STATUS "Conan: Component '${_FIND_COMPONENT}' found in package 'Snappy'")
        endif()
    endforeach()
endif()

########### VARIABLES #######################################################################
#############################################################################################


set(Snappy_INCLUDE_DIRS "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include")
set(Snappy_INCLUDE_DIR "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include")
set(Snappy_INCLUDES "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include")
set(Snappy_RES_DIRS )
set(Snappy_DEFINITIONS )
set(Snappy_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(Snappy_COMPILE_DEFINITIONS )
set(Snappy_COMPILE_OPTIONS_LIST "" "")
set(Snappy_COMPILE_OPTIONS_C "")
set(Snappy_COMPILE_OPTIONS_CXX "")
set(Snappy_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(Snappy_LIBRARIES "") # Will be filled later
set(Snappy_LIBS "") # Same as Snappy_LIBRARIES
set(Snappy_SYSTEM_LIBS stdc++)
set(Snappy_FRAMEWORK_DIRS )
set(Snappy_FRAMEWORKS )
set(Snappy_FRAMEWORKS_FOUND "") # Will be filled later
set(Snappy_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(Snappy_FRAMEWORKS_FOUND "${Snappy_FRAMEWORKS}" "${Snappy_FRAMEWORK_DIRS}")

mark_as_advanced(Snappy_INCLUDE_DIRS
                 Snappy_INCLUDE_DIR
                 Snappy_INCLUDES
                 Snappy_DEFINITIONS
                 Snappy_LINKER_FLAGS_LIST
                 Snappy_COMPILE_DEFINITIONS
                 Snappy_COMPILE_OPTIONS_LIST
                 Snappy_LIBRARIES
                 Snappy_LIBS
                 Snappy_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to Snappy_LIBS and Snappy_LIBRARY_LIST
set(Snappy_LIBRARY_LIST snappy)
set(Snappy_LIB_DIRS "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_Snappy_DEPENDENCIES "${Snappy_FRAMEWORKS_FOUND} ${Snappy_SYSTEM_LIBS} ")

conan_package_library_targets("${Snappy_LIBRARY_LIST}"  # libraries
                              "${Snappy_LIB_DIRS}"      # package_libdir
                              "${_Snappy_DEPENDENCIES}"  # deps
                              Snappy_LIBRARIES            # out_libraries
                              Snappy_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "Snappy")                                      # package_name

set(Snappy_LIBS ${Snappy_LIBRARIES})

foreach(_FRAMEWORK ${Snappy_FRAMEWORKS_FOUND})
    list(APPEND Snappy_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND Snappy_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${Snappy_SYSTEM_LIBS})
    list(APPEND Snappy_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND Snappy_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(Snappy_LIBRARIES_TARGETS "${Snappy_LIBRARIES_TARGETS};")
set(Snappy_LIBRARIES "${Snappy_LIBRARIES};")

set(CMAKE_MODULE_PATH "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/" ${CMAKE_PREFIX_PATH})


########### COMPONENT snappy VARIABLES #############################################

set(Snappy_snappy_INCLUDE_DIRS "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include")
set(Snappy_snappy_INCLUDE_DIR "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include")
set(Snappy_snappy_INCLUDES "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/include")
set(Snappy_snappy_LIB_DIRS "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/lib")
set(Snappy_snappy_RES_DIRS )
set(Snappy_snappy_DEFINITIONS )
set(Snappy_snappy_COMPILE_DEFINITIONS )
set(Snappy_snappy_COMPILE_OPTIONS_C "")
set(Snappy_snappy_COMPILE_OPTIONS_CXX "")
set(Snappy_snappy_LIBS snappy)
set(Snappy_snappy_SYSTEM_LIBS stdc++)
set(Snappy_snappy_FRAMEWORK_DIRS )
set(Snappy_snappy_FRAMEWORKS )
set(Snappy_snappy_BUILD_MODULES_PATHS )
set(Snappy_snappy_DEPENDENCIES )
set(Snappy_snappy_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)


########## FIND PACKAGE DEPENDENCY ##########################################################
#############################################################################################

include(CMakeFindDependencyMacro)


########## FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #######################################
#############################################################################################

########## COMPONENT snappy FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Snappy_snappy_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Snappy_snappy_FRAMEWORKS_FOUND "${Snappy_snappy_FRAMEWORKS}" "${Snappy_snappy_FRAMEWORK_DIRS}")

set(Snappy_snappy_LIB_TARGETS "")
set(Snappy_snappy_NOT_USED "")
set(Snappy_snappy_LIBS_FRAMEWORKS_DEPS ${Snappy_snappy_FRAMEWORKS_FOUND} ${Snappy_snappy_SYSTEM_LIBS} ${Snappy_snappy_DEPENDENCIES})
conan_package_library_targets("${Snappy_snappy_LIBS}"
                              "${Snappy_snappy_LIB_DIRS}"
                              "${Snappy_snappy_LIBS_FRAMEWORKS_DEPS}"
                              Snappy_snappy_NOT_USED
                              Snappy_snappy_LIB_TARGETS
                              ""
                              "Snappy_snappy")

set(Snappy_snappy_LINK_LIBS ${Snappy_snappy_LIB_TARGETS} ${Snappy_snappy_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/chrissi/.conan/data/snappy/1.1.9/_/_/package/6557f18ca99c0b6a233f43db00e30efaa525e27e/" ${CMAKE_PREFIX_PATH})


########## TARGETS ##########################################################################
#############################################################################################

########## COMPONENT snappy TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Snappy::snappy)
        add_library(Snappy::snappy INTERFACE IMPORTED)
        set_target_properties(Snappy::snappy PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Snappy_snappy_INCLUDE_DIRS}")
        set_target_properties(Snappy::snappy PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Snappy_snappy_LIB_DIRS}")
        set_target_properties(Snappy::snappy PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Snappy_snappy_LINK_LIBS};${Snappy_snappy_LINKER_FLAGS_LIST}")
        set_target_properties(Snappy::snappy PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Snappy_snappy_COMPILE_DEFINITIONS}")
        set_target_properties(Snappy::snappy PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Snappy_snappy_COMPILE_OPTIONS_C};${Snappy_snappy_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## GLOBAL TARGET ####################################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    if(NOT TARGET Snappy::Snappy)
        add_library(Snappy::Snappy INTERFACE IMPORTED)
    endif()
    set_property(TARGET Snappy::Snappy APPEND PROPERTY
                 INTERFACE_LINK_LIBRARIES "${Snappy_COMPONENTS}")
endif()

########## BUILD MODULES ####################################################################
#############################################################################################
########## COMPONENT snappy BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Snappy_snappy_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
